plugins {
  id 'com.android.library'
  id 'org.jetbrains.kotlin.android'
}

group = 'org.bondfires.nowplayinginfo'
version = '0.1.0'

android {
  namespace 'org.bondfires.nowplayinginfo'
  compileSdk 35

  defaultConfig {
    minSdk 24
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'androidx.media:media:1.8.0'
}
