import { Button, Text } from '@bondfires/ui'
import { Check, Copy, Share, X } from '@tamagui/lucide-icons'
import { useMutation } from 'convex/react'
import * as Clipboard from 'expo-clipboard'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Alert, Pressable, Share as RNShare } from 'react-native'
import { Sheet, Spinner, XStack, YStack } from 'tamagui'
import { api } from '../../../convex/_generated/api'
import type { Id } from '../../../convex/_generated/dataModel'

interface Props {
  campId: Id<'camps'>
  open: boolean
  onClose: () => void
}

const INVITE_BASE_URL = 'https://bondfires.app/invite/camp'

export function CampInviteSheet({ campId, open, onClose }: Props) {
  const [inviteCode, setInviteCode] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const hasAutoGeneratedRef = useRef(false)
  const previousCampIdRef = useRef(campId)
  const createInvite = useMutation(api.camps.createInvite)

  const generateInvite = useCallback(async () => {
    if (loading) return
    setLoading(true)
    try {
      const result = await createInvite({ campId })
      setInviteCode(result.code)
    } catch (error) {
      Alert.alert('Invite Failed', error instanceof Error ? error.message : String(error))
    } finally {
      setLoading(false)
    }
  }, [campId, createInvite, loading])

  useEffect(() => {
    if (previousCampIdRef.current === campId) return
    previousCampIdRef.current = campId
    setInviteCode(null)
    setCopied(false)
    setLoading(false)
    hasAutoGeneratedRef.current = false
  }, [campId])

  useEffect(() => {
    if (!open || inviteCode || loading || hasAutoGeneratedRef.current) return
    hasAutoGeneratedRef.current = true
    void generateInvite()
  }, [generateInvite, inviteCode, loading, open])

  const inviteUrl = inviteCode ? `${INVITE_BASE_URL}/${inviteCode}` : null

  const handleCopy = useCallback(async () => {
    if (!inviteUrl) return
    try {
      await Clipboard.setStringAsync(inviteUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      Alert.alert('Copy Failed', error instanceof Error ? error.message : String(error))
    }
  }, [inviteUrl])

  const handleShare = useCallback(async () => {
    if (!inviteUrl || !inviteCode) return
    try {
      await RNShare.share({
        message: `Join my camp on Bondfires!\n\nUse this link: ${inviteUrl}\n\nOpen the Bondfires app and enter this code to join.`,
        url: inviteUrl,
      })
    } catch (error) {
      Alert.alert('Share Failed', error instanceof Error ? error.message : String(error))
    }
  }, [inviteUrl, inviteCode])

  return (
    <Sheet
      open={open}
      onOpenChange={(isOpen: boolean) => {
        if (!isOpen) onClose()
      }}
      snapPoints={[55]}
      dismissOnSnapToBottom
    >
      <Sheet.Overlay backgroundColor="rgba(0,0,0,0.45)" />
      <Sheet.Frame
        backgroundColor={'$backgroundPress'}
        borderTopLeftRadius={20}
        borderTopRightRadius={20}
        padding={24}
      >
        <YStack gap={20}>
          <Sheet.Handle backgroundColor={'$borderColor'} />

          <Text fontSize={22} fontWeight="900" textAlign="center">
            Invite Someone
          </Text>
          <Text fontSize={14} color={'$placeholderColor'} textAlign="center" lineHeight={20}>
            This camp is invite-only. Share this link so someone can join.
          </Text>

          {loading ? (
            <YStack alignItems="center" paddingVertical={24} gap={12}>
              <Spinner size="large" color={'$primary'} />
              <Text color={'$placeholderColor'}>Generating invite...</Text>
            </YStack>
          ) : inviteCode ? (
            <YStack gap={16} alignItems="center">
              <YStack
                backgroundColor={'$backgroundHover'}
                borderWidth={1}
                borderColor={'$borderColor'}
                borderRadius={14}
                paddingHorizontal={24}
                paddingVertical={16}
                alignItems="center"
                gap={8}
              >
                <Text
                  fontSize={12}
                  color={'$placeholderColor'}
                  fontWeight="600"
                  textTransform="uppercase"
                  letterSpacing={1}
                >
                  Your Invite Code
                </Text>
                <Text fontSize={32} fontWeight="900" letterSpacing={2} color={'$gray12'}>
                  {inviteCode}
                </Text>
                <Text fontSize={12} color={'$placeholderColor'} numberOfLines={1}>
                  {inviteUrl}
                </Text>
              </YStack>

              <XStack gap={12} width="100%">
                <Button
                  variant="outline"
                  flex={1}
                  onPress={handleCopy}
                  icon={
                    copied ? (
                      <Check size={18} color={'$success'} />
                    ) : (
                      <Copy size={18} color={'$gray12'} />
                    )
                  }
                >
                  <Text color={copied ? '$success' : '$gray12'} fontWeight="700">
                    {copied ? 'Copied' : 'Copy Link'}
                  </Text>
                </Button>
                <Button
                  variant="primary"
                  flex={1}
                  onPress={handleShare}
                  icon={<Share size={18} color={'$gray12'} />}
                >
                  <Text color={'$gray12'} fontWeight="700">
                    Share
                  </Text>
                </Button>
              </XStack>
            </YStack>
          ) : (
            <YStack alignItems="center" paddingVertical={24}>
              <Button variant="primary" onPress={generateInvite}>
                <Text color={'$gray12'} fontWeight="700">
                  Generate Invite
                </Text>
              </Button>
            </YStack>
          )}

          <Pressable onPress={onClose} style={{ alignSelf: 'center' }}>
            <YStack
              width={40}
              height={40}
              borderRadius={20}
              backgroundColor={'$backgroundHover'}
              alignItems="center"
              justifyContent="center"
            >
              <X size={20} color={'$placeholderColor'} />
            </YStack>
          </Pressable>
        </YStack>
      </Sheet.Frame>
    </Sheet>
  )
}
